### ISSUE TITLE
Analaysis "fails" if no visualizations are created

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#15]
Creating visualizations is an optional feature (actually, there's a checkbox before submitting the analysis for this).

Additionally, for `ssGSEA` analyses we never create visualizations if there are more than `N` samples.

## Issue

Currently, the pathway browser shows an error message if the visualizations are missing.

## Wanted behaviour

  * Once the analysis is done, state the no visualizations where created and that the pathway view therefore is unavailable
  * Load the reports

**Comment by jgriss** [comment]
Hi @EliotRagueneau 

You actually did reproduce the issue. There are two reasons why we do not create visualizations:

  1. The user disables the feature in the checkbox
  2. In `ssGSEA` we automatically disable this feature on the server side if there are too many samples.

The error you posted should not occur. Instead, there should be a "normal" message, that no visualizations were created but the reports should be loaded normally.

**Comment by EliotRagueneau** [comment]
Fix deployed at https://dev.reactome.org/PathwayBrowser/#/TOOL=AT

**Comment by jgriss** [comment]
Looks perfect!
