### ISSUE TITLE
GreinFetcher returns invalid expression value table

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#39]
The GreinFetcher currently returns an invalid expression table.

## Required format

The required format is:
  * First column gene id (ideally ensemble gene)
  * Any subsequent column must represent one sample (header = title)

## Current format

The expression value table starts with two columns describing the gene. Once with the ENSEMBL id and once with the gene symbol

## Solution

Remove gene symbol column from table before converting it to a string

**Comment by alexgrent** [comment]
removed gene_symbol column
