### ISSUE TITLE
Some GREIN datasets fail due to invalid summary

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#40]
## Description

Loading some GREIN datasets fails due to an "invalid summary":

```
Failed to load dataset: Failed to load a valid summary for GSE148842
```

## Required changes

  * Test if all datasets can be supported
  * Use the logging system to log an error if loading a datasets fails

**Comment by alexgrent** [comment]
The dataset can not be processed from GREIN. Therefore the response we get from GREIN is invalid. 
The dataset GSE148842 has no metadata or count_matrix, therefore it is processed as invalid in the grein_fetcher. 
<img width="441" alt="image" src="https://github.com/reactome/gsa-backend/assets/51237839/6f09f090-20e1-4df6-b5ba-597ea4ac743a">

**Comment by alexgrent** [comment]
fix for this issue on branch 40-some-grein-datasets-fail-due-to-invalid-summary-1

**Comment by jgriss** [comment]
Great! Thanks a lot! Running CI tests
