### ISSUE TITLE
Create fulltext search function for supported public datasets

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#43]
## API Endpoint

  * Define API search endpoint
  * Define search result format
    * Include search result (ie. information to load dataset, title, species, description)
  * ? Create API search suggestion endpoint (search term suggestions, spelling correction)

## Search function

  * Implemented as part of the API pod - must work without external resources to keep latency as low as possible
  * Test [Whoosh](https://whoosh.readthedocs.io/) to implement search function (would include error correction)
  * Define index building strategy:
    * Option 1: Build during pod startup. Advantage: up-to-date search index, Disadvantage: longer startup time
    * Option 2: Build once during Docker image creation.

**Comment by jgriss** [comment]
I'd rather return the search result as a list of `dict`s. This essentially then represents a list of objects where each object is a search result. Generally, this is much easier to parse compared to having one list per field.

We need to think about how to define the id's. The web application needs 2 pieces of information to actually load an external dataset:

  * the id of the resource (ie. grein)
  * the parameter(s) for this

Generally, we use the `dataset_id` as the main parameter. But the SingleCellExpressionAtlas fetcher, f.e., also needs the parameter `k` to be set.

**Comment by alexgrent** [comment]
Search functionality is implemented in public_data_searcher.py. The current search approach is searching by keywords in title, species and description. But limiting the search results to 100.
