### ISSUE TITLE
Add support for GEOquery to load microarray studies from GEO

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#49]
## Idea

[GEOquery](https://bioconductor.org/packages/release/bioc/html/GEOquery.html) can be used to easily load microarray-based studies from GEO.

This data can be easily incorporated into ReactomeGSA analysis (see example [here](https://github.com/reactome/ReactomeGSA-tutorials/blob/master/notebooks/ReactomeGSA-Immunology_Example.ipynb)

## ToDo

  - [x] Create new DatasetFetcher using GEOquery
  - [x] Implement method to detect data type correctly (MicroArray vs. RNA-seq)
 
## Note

Search functionality will not be possible for this package as it directly accesses GEO. Only when accessing a project we know whether it's fully supported.

**Comment by alexgrent** [comment]
In this case the first approach is to check if it is possible to use existing python packages e.g. GEOparse, 
otherwise use packages e.g. rpy2 to embedded the provided R script.

**Comment by alexgrent** [comment]
New load_dataset method is added.
We should discuss the following points:

- What to return instead of the count matrix -> currently an empty string is returned 
- The GEOparse.get_geo() downloads the files,  problems might occur with this approach -> maybe implement a clean up method
- Fetching GEO data (with the download) takes a while depending on the size of the dataset

**Comment by alexgrent** [comment]
Current Status: 
Data can be requested from geo with the geo_fetcher in the dataset fetchers.

The design issues from the comment above still need to be discussed.

**Comment by alexgrent** [comment]
Additionally, I implemented a request which also allows to fetch the expression values, if a filename is given. This would require the name of the file with the expression values.

**Comment by alexgrent** [comment]
@mitrazad as discussed in the meeting. 
R package to download the matrix: https://bioconductor.org/packages/release/bioc/html/GEOquery.html 
python package:  https://geoparse.readthedocs.io/en/latest/GEOparse.html

**Comment by jgriss** [comment]
Hi @alexgrent ,

Just tested the updated version. The loaded expression values are currently invalid. The table misses the gene_ids as the first column. Additionally, the sample names (values of the first row) do not match the metadata
