### ISSUE TITLE
Create whitelist of working GREIN datasets

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#50]
GREIN contains a comparably large number of not working datasets in their index

## TODO

Create an index where we store all datasets that actually work

This index should be used as a whitelist when creating the search index

**Comment by alexgrent** [comment]
The approach is the following
- [ ] write a script which tests all grein datasets
- [ ] incorporate the list in the grein fetcher and index build

**Comment by alexgrent** [comment]
It looks like in some cases it depends on the amalysis method selected. E.g. GSE100007 works with ssGSEA but not with CAMERA

**Comment by jgriss** [comment]
The error concerning `CAMERA` and `GSE100007` points to an issue in the metadata.

![image](https://github.com/reactome/gsa-backend/assets/10997605/3ab475ce-d2f0-4d01-8d77-1c716884624b)

Please double check the returned metadata of this dataset.

In our initial check, we should only assess whether we can load the dataset - there seem to be enough datasets listed in the index that are actually not available. Catching these, would be sufficient in a first step

**Comment by jgriss** [comment]
**Note**: Issue with `GSE10007` is linked to #52

**Comment by alexgrent** [comment]
[grein_test_script.py.zip](https://github.com/reactome/gsa-backend/files/12803216/grein_test_script.py.zip)

**Comment by alexgrent** [comment]
[whitelist_filtered.txt](https://github.com/reactome/gsa-backend/files/13213176/whitelist_filtered.txt)
