### ISSUE TITLE
More steps in the report creation if possible

### ISSUE THREAD

**Issue by EliotRagueneau** [reactome/gsa-backend#58]
Hi,

Henning thought the application was bugging because when you ask for reports to be created, the loader stays at 10% for quite a while, do you think it would be possible to add more intermediate steps for this loader? like maybe adding 1/3 of the progress for each different report format being created?

Best regards,
Eliot

**Comment by jgriss** [comment]
This is now fixed. Additional progress steps are shown - so it looks more interactive :-)
