### ISSUE TITLE
Set reports FDR threshold 0.05 to match the actual data display

### ISSUE THREAD

**Issue by EliotRagueneau** [reactome/gsa-backend#61]
At the moment, if the regulation FDR value is at 0.02, the pathway will be marked as significantly up/down regulated in the view (bright colors + ▲▲ in the table ), while in the excel reports, it is marked as significant: FALSE since the threshold is there set at 0.01.

We want to unify displayed results with reports data, so use the same threshold.

Additionally, if you could add another column in the Excel sheet per dataset just containing the arrows, that would be great to have a similar aspect than the table in Reactome
| pValue | Fold change | Symbol |
|--------|--------|:------:|
| < 0.05 |  + | ▲▲ |
| > 0.05 | + | ▲ |
| - | 0 | - |
| > 0.05 | - | ▼ |
| < 0.05 | - | ▼▼ |

**Comment by jgriss** [comment]
@EliotRagueneau This is now fixed - both in the PDF report as well as the Excel sheet

**Comment by EliotRagueneau** [comment]
Awesome ! Thanks a lot :D
